version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: and07_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/home/and07/docker/btc.yoga
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/snippets:/etc/nginx/snippets
      - /var/logs/nginx:/var/logs/nginx
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl/certs/:/etc/ssl/certs/
    depends_on:
      - web
  web:
    image: rss2website
    container_name: and07_rss2site
    build: .
    ports:
      - 3000:3000