FROM golang

# Install
RUN go get github.com/gorilla/mux && go get github.com/gosimple/slug && go get github.com/mmcdole/gofeed

# Set the entry point of the container to the bee command that runs the
# application and watches for changes
# Build the outyet command inside the container.
# (You may fetch or manage dependencies here,
# either manually or with a tool like "godep".)
RUN go install github.com/and07/rss2website

# Run the outyet command by default when the container starts.
ENTRYPOINT /go/bin/rss2website

# Expose the application on port 3000
EXPOSE 3000